prathimacode-hub/IoT-Spot

README.md
I have added a few changes in grammar, in the README.md File. Please do review
=> Gramatical Changes in README.md

README.md
=> fixed hyperlink

index.html
=> Fixed some Spells and errors

assets/css/style.css, assets/js/vanilla-tilt.js, index.html
Issue #78 
- Add animation effect to IoT main image
Closes: #78 
Added tilt effect animation on hovering on the IoT main-img
Running on Local host 
##Screenshot:
=> added tilt effect to main-img

index.html
Closes #123 
- Added dynamic counter works whenever the user scrolls down on that div.
- Improves UI of website.
- Also Added Icons that improve the overall look.
=> #123 Done : Added Dynamic Counter

assets/blog.html, assets/css/blog.css
This pull request is associated to  the issue #149
1. Added footer in blog page.
2. Added smooth transition effect on hovering over the cards in blog page.
=> Added footer in blog page

assets/css/style.css
I have added hover effect in all the favicon of home page and blog page.
Fixes #125 
**Test Configuration**:
- Operating system:
- Version:
- Text-editors used:
=> Added hover effect in favicon

index.html
I have improved the working of About us and Contact us button in home page.  Now the button will work even if we click on the button and not only the text in button.
Fixes #128 
**Test Configuration**:
- Operating system:
- Version:
- Text-editors used:
=> Improved working of button in home page

IoT-Spot Website/assets/css/style.css, assets/css/style.css
- #142 Changing css of scrollbar .
Closes: #142 
I have changed the css and styling of the scrollbar which aligns with the theme of website . Moreover , its color changes on hovering over it .
On hovering the color of scrollbar changes
Without hovering over it
|
=> Solved issue #142 . Made changes in css of scrollbar.

8051/Documentation/Introduction to 8051/README.md
Closes: #183
Added new project - Introduction to 8051 Microcontroller
Describe how have you verified the changes made
<br>
Made a word file, included information from various web sources as well as from material already I had. The motive was to deliver the best content regarding the 8051 Microcontroller.
<br>
Document Snippets:
Original           | Updated
:--------------------: |:--------------------:
Original Screenshot | Updated Screenshot |
Original Block Diagram | Updated Block Diagram |
Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |
=> Introduction to 8051 Microcontroller 

assets/css/hamburger.css, assets/css/style.css, index.html
Fixes #219 
Improved the mobile version of website, changed all the proposal which were made in issue.
Screenshots :
=> Improved Mobile view of website

assets/css/style.css, index.html
I have fixed working of button and added hover effect in favicon of footer.
Fixes #204  
**Test Configuration**:
- Operating system:
- Version:
- Text-editors used:
=> 204 improve button and hover

assets/css/style.css
Closes: #issue number that will be closed through this PR
Give a clear description what modifications you have made
Describe how have you verified the changes made
Original           | Updated
:--------------------: |:--------------------:
Original Screenshot | Updated Screenshot |
Original Block Diagram | Updated Block Diagram |
Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram 
|
=> Scroll bar added

assets/blog.html, assets/css/blog.css
Updated blog page UI and Added more blogs
#82 
1)I added 6  blogs in the blog section with relevant topics-1) What is IoT? 2)Architecture 3)Real World IoT Applications 4)Top IoT Projects 5)IoT Courses 6)Future of IoT  and relevant images and links added to read particular blog.
2)Made the "Back To Home" active on blog page in nav-bar .Earlier it was not redirecting to index.html after clicking on it.
3)After hovering on particular blog and also on image there is some Y-transform, box shadow effect .
4)After hovering on Image of blog height of image increases which makes it look good.
5)After hovering on Read More button, color of button changes according to website theme.
6))Earlier the footer was not aligned properly so made it proper.
I made all the required changes and PR .Please …
=> Blog Section Updated

IoT-Spot Website/assets/css/style.css
Closes: #69
I observed that previously the site is not responsive for medium screens , images and content get stack over each other.
I have fixed the issues by adding some media query's which will make the site responsive for medium screen too.
I have run the code before and after adding my code and observe the changes which is making it bug free. 
before
After
Original           | Updated
:--------------------: |:--------------------:
Original Screenshot | Updated Screenshot |
Original Block Diagram | Updated Block Diagram |
Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |
=> Solve the problem of stack of image and content

IoT-Spot Website/assets/css/style.css
Currently when we hover over the option it has black background.
And in contact page it has gray background with black color input which decreses the visisbility.
About and contact us button also doesn't have great effect which tells that button is clicked or not 
Closes: #253
1.Improve the CSS part of navigation tabs by matching website theme, which makes it more attractive.
2.Add animation, pressed affect over about and contact us button which makes it more clear when button got pressed.
3.By changing te colors of contact us background and making send mail button more attractive.
4.Make Inclusion part little hoverable
My observing the functioning of code before and after the changes
https://user-images.githubusercontent.com/96954912/171105068-2a44ae28-8 …
=> Improved the CSS part of navigation tabs, contact page and buttons.

Raspberry Pi/Display-Time-in-LCD/README.md, Raspberry Pi/Display-Time-in-LCD/requirements.txt, Raspberry Pi/Display-Time-in-LCD/time.py
Closes: #169  that will be closed through this PR
Added files for the project Display Time on LCD using Raspberry PI 
=> Display Time in LCD

.github/workflows/pages.yml
The website doesn't works currently on the link https://prathimacode-hub.github.io/IoT-Spot/
I have tried the github Action on my fork which looks good for the website and you can preview it here https://harshil-jani.github.io/IoT-Spot/#
But I doubt if the current Action on this repo fails and even the new Action after the merge of this PR doesn't works then We manually need to remove the failing action and replace it simply with the action from this PR.
=> Fix Github Actions for Website

IoT-Spot Website/assets/css/style.css
Scroll bar which was present in the X direction has been removed.
Closes: #273
Give a clear description what modifications you have made
Some changes in the CSS file has been made.
Describe how have you verified the changes made
Hosting repo in local host.
=> CSS File updated, Scroll bar in X axis is removed.

IoT-Spot Website/assets/css/style.css, assets/css/style.css, index.html
Added links for the projects section and also added a red hover for the links
=> Added links for the projects section issue #267

IoT-Spot Website/assets/css/style.css, IoT-Spot Website/index.html, index.html
Fixes issue #279 
**Info about the related issue**
The issue was to improve the navbar hover effects.
**Describe the changes you've made**
I have worked on the navbar hover effect, which is matching with the page UI.
**What sort of change have you made**
New feature (non-breaking change which adds functionality)
Code style update (formatting, local variables)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update
**How Has This Been Tested ?**
I have tested all the changes in my local file and it worked well.
**Checklist:**
**Screenshots**
=> Improved navbar hover effects

IoT-Spot Website/assets/check-circle.svg, IoT-Spot Website/assets/css/style.css, IoT-Spot Website/index.html, index.html
Fixes issue #286  
**Info about the related issue**
The issue was to improve the Inclusion section.
**Describe the changes you've made**
I have worked on improvement of user interface and design of inclusion section.
**What sort of change have you made**
New feature (non-breaking change which adds functionality)
Code style update (formatting, local variables)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update
**How Has This Been Tested ?**
I have tested all the changes in my local file and it worked well.
**Checklist:**
**Screenshots**
=> Improving Inclusion section

IoT-Spot Website/assets/css/style.css
fixed the navigation bar, align the elements, changed the font size and weight. Fixes #295
=> Issue name: Navigation bar UI

ESP32/Temperature Humidity measure using ESP32/DHT22_Serial_monitor/DHT22_Serial_monitor.ino, ESP32/Temperature Humidity measure using ESP32/DHT22_Web_server/DHT22_Web_server.ino, ESP32/Temperature Humidity measure using ESP32/README.md
Closes: #312 
Added both DHT22 operation on ESP32 and it prints data on Serial monitor as well as Web server
It has been tested in the hardware mode and also in [simulation](https://wokwi.com/projects/342713692783116883)
=> Measuring Temperature and Humidity with DHT22 on a ESP32

IoT-Spot Website/assets/css/style.css
Fixed X scroll (There was some mistake in commiting the code previous time)
=> Fixed X scroll (issue #273)

IoT-Spot Website/assets/css/style.css, index.html
Solves issue #301
I created an Issue earlier regarding how the layout of the IoT Spot website was too stretched and Out of the screen this PR is for that I have fixed the issue and made it much more centered for all the screens here are a few :
=> Centered the content of main page

ESP32/README.md
Closes: #328
For the README for ESP32, I have added various info regarding the board and links which may prove to be helpful for the developer when designing any circuitry employing the ESP32.
=> Updating ReadMe of ESP32 folder with information
